site_name: 华零的blog
theme:
  name: material
  favicon: assets/fav.jpg
  logo: assets/fav.jpg
  features: 
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  language: 'zh'
  custom_dir: overrides
  font: 
    text: Noto Serif SC # Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
nav:
  - 主页: # 主页/
    - index.md
  - CS selflearning: 
    - 国内外著名课程/computer crash course.md
    - CS61B:
      - 国内外著名课程/CS61B/preparation for the lesson.md
      - 国内外著名课程/CS61B/learning Java.md
      - 国内外著名课程/CS61B/oop.md
      - 国内外著名课程/CS61B/data structure/data structure.md
    - computer systems:
      - 国内外著名课程/computer system/preparation.md
      - 国内外著名课程/computer system/CS61C great idea in computer architecture.md
    - database system:
      - 国内外著名课程/cmu15445/advanced C++.md
      - 国内外著名课程/cmu15445/SQL.md
      - 国内外著名课程/cmu15445/DB design.md
      - 国内外著名课程/cmu15445/disk storage.md
      - 国内外著名课程/cmu15445/Concurrency and recovery.md
      - 国内外著名课程/cmu15445/MiniSQL 概述.md
    - mit weblab:
      - 国内外著名课程/MIT weblab/web basic.md
      - 国内外著名课程/MIT weblab/react.md
      - 国内外著名课程/MIT weblab/Nodejs.md
    - computer security:
      - 国内外著名课程/cs161/index.md
      - 国内外著名课程/cs161/CS161 computer security.md
    - computer vision:
      - 国内外著名课程/computer vision/index.md
      - 国内外著名课程/computer vision/UMich EECS 498-007 Deep Learning for Computer Vision.md
    - operation system:
      - 国内外著名课程/rcore/rCore 清华操作系统实验.md
    - artificial intelligence:
      - 国内外著名课程/AI/线性回归/线性回归.md
      - 国内外著名课程/AI/基础的多层神经网络/基础的多层神经网络.md
    - 国内外著名课程/CS110L/CS110L.md
  - ZJU-course: 
    - ZJU-course/Discrete Mathematics.md
    - ZJU-course/计概/Introduction to Computing Systems_ From Bits & Gates to C & Beyond.md
    - ZJU-course/计原/计原.md
    - ZJU-course/fds/FDS.md
    - ZJU-course/oop 期末复习/oop 期末复习.md
    - ZJU-course/信息安全原理/信息安全原理.md
    - ZJU-course/数据库系统期末/数据库系统期末复习.md
    - ZJU-course/ADS/ADS.md
    - ZJU-course/软工面试准备资料.md
    - 通识课程:
      - ZJU-course/通识课程/中国书法史/中国书法史.md
    
  - 技术积累:
    - 语言基础:
      - 技术积累/语言基础/C++ note.md/C++ note.md
      - 技术积累/语言基础/Rust 入门/Rust 入门.md
      - 技术积累/语言基础/python 入门/python 入门.md
    - 实用技能:
      - 技术积累/实用技能/git and github.md/git and github.md
  - 我的碎碎念:
     - 生活上的碎碎念/大二上课程总结.md


markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - CSS/admonition.css
  - CSS/other.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hzeroyuke?tab=repositories
      name: hzeroyuke's github
repo_url: https://github.com/hzeroyuke?tab=repositories
repo_name: hzeroyuke's github


extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
