site_name: My Docs
theme:
  name: material
  features: 
    - navigation.tabs # 一级导航栏横放置
nav:
  - 主页: # 主页/
    - 主页/index.md
  - 国外著名课程: 
    - 国外著名课程/computer crash course.md
  - ZJU-course: 
    - ZJU-course/Discrete Mathematics.md