site_name: 华零的blog
theme:
  name: material
  favicon: assets/fav.jpg
  logo: assets/fav.jpg
  features: 
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  language: 'zh'
  custom_dir: overrides
  font: 
    text: Noto Serif SC # Roboto
    code: Roboto Mono
  palette: 
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    #- scheme: slate
    #  toggle:
    #    icon: material/toggle-switch-off-outline
    #    name: Switch to light mode
nav:
  - 主页: # 主页/
    - index.md
  - CS selflearning: 
    - 国外著名课程/computer crash course.md
    - CS61B:
      - 国外著名课程/CS61B/preparation for the lesson.md
      - 国外著名课程/CS61B/learning Java.md
      - 国外著名课程/CS61B/oop.md
      - 国外著名课程/CS61B/data structure/data structure.md
    - computer systems:
      - 国外著名课程/computer system/preparation.md
      - 国外著名课程/computer system/CS61C great idea in computer architecture.md
    - cmu15445:
      - 国外著名课程/cmu15445/advanced C++.md
  - ZJU-course: 
    - ZJU-course/Discrete Mathematics.md
    - ZJU-course/计概/Introduction to Computing Systems_ From Bits & Gates to C & Beyond.md
    - ZJU-course/计原/计原.md
    - ZJU-course/fds/FDS.md
    - ZJU-course/oop 期末复习/oop 期末复习.md
    - ZJU-course/软工面试准备资料.md
    
  - 技术积累:
    - 语言基础:
      - 技术积累/语言基础/C++ note.md/C++ note.md
    - 实用技能:
      - 技术积累/实用技能/git and github.md/git and github.md
  - 我的碎碎念:
     - 生活上的碎碎念/大二上课程总结.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - CSS/admonition.css
  - CSS/other.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hzeroyuke?tab=repositories
      name: hzeroyuke's github
repo_url: https://github.com/hzeroyuke?tab=repositories
repo_name: hzeroyuke's github

